-- Climate seed data for Supabase
INSERT INTO public.mdall_climate_snow_canton_overrides (department_code, canton_name, canton_name_normalized, resolved_zone, source_payload)
VALUES
  ('01', 'Bâgé-le-Châtel', 'bage le chatel', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Bâgé-le-Châtel"}'::jsonb),
  ('01', 'Bourg-en-Bresse (tous cantons)', 'bourg en bresse (tous cantons)', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Bourg-en-Bresse (tous cantons)"}'::jsonb),
  ('01', 'Chalamont', 'chalamont', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Chalamont"}'::jsonb),
  ('01', 'Châtillon-sur-Chalaronne', 'chatillon sur chalaronne', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Châtillon-sur-Chalaronne"}'::jsonb),
  ('01', 'Coligny', 'coligny', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Coligny"}'::jsonb),
  ('01', 'Meximieux', 'meximieux', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Meximieux"}'::jsonb),
  ('01', 'Miribel', 'miribel', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Miribel"}'::jsonb),
  ('01', 'Montluel', 'montluel', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Montluel"}'::jsonb),
  ('01', 'Montrevel-en-Bresse', 'montrevel en bresse', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Montrevel-en-Bresse"}'::jsonb),
  ('01', 'Péronnas', 'peronnas', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Péronnas"}'::jsonb),
  ('01', 'Pont-d''Ain', 'pont d ain', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Pont-d''Ain"}'::jsonb),
  ('01', 'Pont-de-Vaux', 'pont de vaux', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Pont-de-Vaux"}'::jsonb),
  ('01', 'Pont-de-Veyle', 'pont de veyle', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Pont-de-Veyle"}'::jsonb),
  ('01', 'Reyrieux', 'reyrieux', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Reyrieux"}'::jsonb),
  ('01', 'Saint-Trivier-de-Courtes', 'saint trivier de courtes', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Saint-Trivier-de-Courtes"}'::jsonb),
  ('01', 'Saint-Trivier-sur-Moignans', 'saint trivier sur moignans', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Saint-Trivier-sur-Moignans"}'::jsonb),
  ('01', 'Thoissey', 'thoissey', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Thoissey"}'::jsonb),
  ('01', 'Trévoux', 'trevoux', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Trévoux"}'::jsonb),
  ('01', 'Villars-les-Dombes', 'villars les dombes', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Villars-les-Dombes"}'::jsonb),
  ('01', 'Viriat', 'viriat', 'A2', '{"department_code":"01","resolved_zone":"A2","canton_name":"Viriat"}'::jsonb),
  ('01', 'Tous les autres cantons', 'tous les autres cantons', 'C2', '{"department_code":"01","resolved_zone":"C2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('02', 'Aubenton', 'aubenton', 'C1', '{"department_code":"02","resolved_zone":"C1","canton_name":"Aubenton"}'::jsonb),
  ('02', 'La Capelle', 'la capelle', 'C1', '{"department_code":"02","resolved_zone":"C1","canton_name":"La Capelle"}'::jsonb),
  ('02', 'Hirson', 'hirson', 'C1', '{"department_code":"02","resolved_zone":"C1","canton_name":"Hirson"}'::jsonb),
  ('02', 'Tous les autres cantons', 'tous les autres cantons', 'A1', '{"department_code":"02","resolved_zone":"A1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('06', 'Breil-sur-Roya', 'breil sur roya', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Breil-sur-Roya"}'::jsonb),
  ('06', 'Guillaumes', 'guillaumes', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Guillaumes"}'::jsonb),
  ('06', 'Lantosque', 'lantosque', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Lantosque"}'::jsonb),
  ('06', 'Puget-Théniers', 'puget theniers', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Puget-Théniers"}'::jsonb),
  ('06', 'Roquebillière', 'roquebilliere', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Roquebillière"}'::jsonb),
  ('06', 'Saint-Étienne-de-Tinée', 'saint etienne de tinee', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Saint-Étienne-de-Tinée"}'::jsonb),
  ('06', 'Saint-Martin-Vésubie', 'saint martin vesubie', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Saint-Martin-Vésubie"}'::jsonb),
  ('06', 'Saint-Sauveur-sur-Tinée', 'saint sauveur sur tinee', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Saint-Sauveur-sur-Tinée"}'::jsonb),
  ('06', 'Sospel', 'sospel', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Sospel"}'::jsonb),
  ('06', 'Tende', 'tende', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Tende"}'::jsonb),
  ('06', 'Villars-sur-Var', 'villars sur var', 'C1', '{"department_code":"06","resolved_zone":"C1","canton_name":"Villars-sur-Var"}'::jsonb),
  ('06', 'Tous les autres cantons', 'tous les autres cantons', 'A2', '{"department_code":"06","resolved_zone":"A2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('08', 'Asfeld', 'asfeld', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Asfeld"}'::jsonb),
  ('08', 'Attigny', 'attigny', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Attigny"}'::jsonb),
  ('08', 'Buzancy', 'buzancy', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Buzancy"}'::jsonb),
  ('08', 'Château-Porcien', 'chateau porcien', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Château-Porcien"}'::jsonb),
  ('08', 'Chaumont-Porcien', 'chaumont porcien', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Chaumont-Porcien"}'::jsonb),
  ('08', 'Chesne (le)', 'chesne (le)', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Chesne (le)"}'::jsonb),
  ('08', 'Grandpré', 'grandpre', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Grandpré"}'::jsonb),
  ('08', 'Juniville', 'juniville', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Juniville"}'::jsonb),
  ('08', 'Machault', 'machault', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Machault"}'::jsonb),
  ('08', 'Monthois', 'monthois', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Monthois"}'::jsonb),
  ('08', 'Novion-Porcien', 'novion porcien', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Novion-Porcien"}'::jsonb),
  ('08', 'Rethel', 'rethel', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Rethel"}'::jsonb),
  ('08', 'Tourteron', 'tourteron', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Tourteron"}'::jsonb),
  ('08', 'Vouziers', 'vouziers', 'A1', '{"department_code":"08","resolved_zone":"A1","canton_name":"Vouziers"}'::jsonb),
  ('08', 'Tous les autres cantons', 'tous les autres cantons', 'C1', '{"department_code":"08","resolved_zone":"C1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('09', 'Ax-les-Thermes', 'ax les thermes', 'C2', '{"department_code":"09","resolved_zone":"C2","canton_name":"Ax-les-Thermes"}'::jsonb),
  ('09', 'Cabannes (les)', 'cabannes (les)', 'C2', '{"department_code":"09","resolved_zone":"C2","canton_name":"Cabannes (les)"}'::jsonb),
  ('09', 'Lavelanet', 'lavelanet', 'C2', '{"department_code":"09","resolved_zone":"C2","canton_name":"Lavelanet"}'::jsonb),
  ('09', 'Mirepoix', 'mirepoix', 'C2', '{"department_code":"09","resolved_zone":"C2","canton_name":"Mirepoix"}'::jsonb),
  ('09', 'Quérigut', 'querigut', 'C2', '{"department_code":"09","resolved_zone":"C2","canton_name":"Quérigut"}'::jsonb),
  ('09', 'Tous les autres cantons', 'tous les autres cantons', 'A2', '{"department_code":"09","resolved_zone":"A2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('11', 'Belpech', 'belpech', 'C2', '{"department_code":"11","resolved_zone":"C2","canton_name":"Belpech"}'::jsonb),
  ('11', 'Castelnaudary (tous cantons)', 'castelnaudary (tous cantons)', 'C2', '{"department_code":"11","resolved_zone":"C2","canton_name":"Castelnaudary (tous cantons)"}'::jsonb),
  ('11', 'Fanjeaux', 'fanjeaux', 'C2', '{"department_code":"11","resolved_zone":"C2","canton_name":"Fanjeaux"}'::jsonb),
  ('11', 'Salles-sur-l''Hers', 'salles sur l hers', 'C2', '{"department_code":"11","resolved_zone":"C2","canton_name":"Salles-sur-l''Hers"}'::jsonb),
  ('11', 'Tous les autres cantons', 'tous les autres cantons', 'D', '{"department_code":"11","resolved_zone":"D","canton_name":"Tous les autres cantons"}'::jsonb),
  ('25', 'Audeux', 'audeux', 'B1', '{"department_code":"25","resolved_zone":"B1","canton_name":"Audeux"}'::jsonb),
  ('25', 'Besançon (tous cantons)', 'besancon (tous cantons)', 'B1', '{"department_code":"25","resolved_zone":"B1","canton_name":"Besançon (tous cantons)"}'::jsonb),
  ('25', 'Boussières', 'boussieres', 'B1', '{"department_code":"25","resolved_zone":"B1","canton_name":"Boussières"}'::jsonb),
  ('25', 'Marchaux', 'marchaux', 'B1', '{"department_code":"25","resolved_zone":"B1","canton_name":"Marchaux"}'::jsonb),
  ('25', 'Maîche', 'maiche', 'E', '{"department_code":"25","resolved_zone":"E","canton_name":"Maîche"}'::jsonb),
  ('25', 'Morteau', 'morteau', 'E', '{"department_code":"25","resolved_zone":"E","canton_name":"Morteau"}'::jsonb),
  ('25', 'Montbenoît', 'montbenoit', 'E', '{"department_code":"25","resolved_zone":"E","canton_name":"Montbenoît"}'::jsonb),
  ('25', 'Pierrefontaine-les-Varans', 'pierrefontaine les varans', 'E', '{"department_code":"25","resolved_zone":"E","canton_name":"Pierrefontaine-les-Varans"}'::jsonb),
  ('25', 'Russey (le)', 'russey (le)', 'E', '{"department_code":"25","resolved_zone":"E","canton_name":"Russey (le)"}'::jsonb),
  ('25', 'Saint-Hippolyte', 'saint hippolyte', 'E', '{"department_code":"25","resolved_zone":"E","canton_name":"Saint-Hippolyte"}'::jsonb),
  ('25', 'Tous les autres cantons', 'tous les autres cantons', 'C1', '{"department_code":"25","resolved_zone":"C1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('31', 'Revel', 'revel', 'C2', '{"department_code":"31","resolved_zone":"C2","canton_name":"Revel"}'::jsonb),
  ('31', 'Tous les autres cantons', 'tous les autres cantons', 'A2', '{"department_code":"31","resolved_zone":"A2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('34', 'Béziers (tous cantons)', 'beziers (tous cantons)', 'C2', '{"department_code":"34","resolved_zone":"C2","canton_name":"Béziers (tous cantons)"}'::jsonb),
  ('34', 'Capestang', 'capestang', 'C2', '{"department_code":"34","resolved_zone":"C2","canton_name":"Capestang"}'::jsonb),
  ('34', 'Olonzac', 'olonzac', 'C2', '{"department_code":"34","resolved_zone":"C2","canton_name":"Olonzac"}'::jsonb),
  ('34', 'Saint-Chinian', 'saint chinian', 'C2', '{"department_code":"34","resolved_zone":"C2","canton_name":"Saint-Chinian"}'::jsonb),
  ('34', 'Saint-Pons-de-Thomières', 'saint pons de thomieres', 'C2', '{"department_code":"34","resolved_zone":"C2","canton_name":"Saint-Pons-de-Thomières"}'::jsonb),
  ('34', 'Tous les autres cantons', 'tous les autres cantons', 'B2', '{"department_code":"34","resolved_zone":"B2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('39', 'Chaussin', 'chaussin', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Chaussin"}'::jsonb),
  ('39', 'Chemin', 'chemin', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Chemin"}'::jsonb),
  ('39', 'Dampierre', 'dampierre', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Dampierre"}'::jsonb),
  ('39', 'Dole (tous cantons)', 'dole (tous cantons)', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Dole (tous cantons)"}'::jsonb),
  ('39', 'Gendrey', 'gendrey', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Gendrey"}'::jsonb),
  ('39', 'Montbarrey', 'montbarrey', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Montbarrey"}'::jsonb),
  ('39', 'Montmirey-le-Château', 'montmirey le chateau', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Montmirey-le-Château"}'::jsonb),
  ('39', 'Rochefort-sur-Nenon', 'rochefort sur nenon', 'B1', '{"department_code":"39","resolved_zone":"B1","canton_name":"Rochefort-sur-Nenon"}'::jsonb),
  ('39', 'Tous les autres cantons', 'tous les autres cantons', 'C1', '{"department_code":"39","resolved_zone":"C1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('54', 'Arracourt', 'arracourt', 'B1', '{"department_code":"54","resolved_zone":"B1","canton_name":"Arracourt"}'::jsonb),
  ('54', 'Baccarat', 'baccarat', 'B1', '{"department_code":"54","resolved_zone":"B1","canton_name":"Baccarat"}'::jsonb),
  ('54', 'Bayon', 'bayon', 'B1', '{"department_code":"54","resolved_zone":"B1","canton_name":"Bayon"}'::jsonb),
  ('54', 'Blâmont', 'blamont', 'B1', '{"department_code":"54","resolved_zone":"B1","canton_name":"Blâmont"}'::jsonb),
  ('54', 'Gerbéviller', 'gerbeviller', 'B1', '{"department_code":"54","resolved_zone":"B1","canton_name":"Gerbéviller"}'::jsonb),
  ('54', 'Haroué', 'haroue', 'B1', '{"department_code":"54","resolved_zone":"B1","canton_name":"Haroué"}'::jsonb),
  ('54', 'Lunéville (tous cantons)', 'luneville (tous cantons)', 'B1', '{"department_code":"54","resolved_zone":"B1","canton_name":"Lunéville (tous cantons)"}'::jsonb),
  ('54', 'Badonviller', 'badonviller', 'C1', '{"department_code":"54","resolved_zone":"C1","canton_name":"Badonviller"}'::jsonb),
  ('54', 'Cirey-sur-Vezouze', 'cirey sur vezouze', 'C1', '{"department_code":"54","resolved_zone":"C1","canton_name":"Cirey-sur-Vezouze"}'::jsonb),
  ('54', 'Tous les autres cantons', 'tous les autres cantons', 'A1', '{"department_code":"54","resolved_zone":"A1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('55', 'Montmédy', 'montmedy', 'C1', '{"department_code":"55","resolved_zone":"C1","canton_name":"Montmédy"}'::jsonb),
  ('55', 'Stenay', 'stenay', 'C1', '{"department_code":"55","resolved_zone":"C1","canton_name":"Stenay"}'::jsonb),
  ('55', 'Tous les autres cantons', 'tous les autres cantons', 'A1', '{"department_code":"55","resolved_zone":"A1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('57', 'Albestroff', 'albestroff', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Albestroff"}'::jsonb),
  ('57', 'Behren-lès-Forbach', 'behren les forbach', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Behren-lès-Forbach"}'::jsonb),
  ('57', 'Château-Salins', 'chateau salins', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Château-Salins"}'::jsonb),
  ('57', 'Dieuze', 'dieuze', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Dieuze"}'::jsonb),
  ('57', 'Fénétrange', 'fenetrange', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Fénétrange"}'::jsonb),
  ('57', 'Forbach', 'forbach', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Forbach"}'::jsonb),
  ('57', 'Freyming-Merlebach', 'freyming merlebach', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Freyming-Merlebach"}'::jsonb),
  ('57', 'Grostenquin', 'grostenquin', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Grostenquin"}'::jsonb),
  ('57', 'Réchicourt-le-Château', 'rechicourt le chateau', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Réchicourt-le-Château"}'::jsonb),
  ('57', 'Rohrbach-lès-Bitche', 'rohrbach les bitche', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Rohrbach-lès-Bitche"}'::jsonb),
  ('57', 'Saint-Avold (tous cantons)', 'saint avold (tous cantons)', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Saint-Avold (tous cantons)"}'::jsonb),
  ('57', 'Sarralbe', 'sarralbe', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Sarralbe"}'::jsonb),
  ('57', 'Sarreguemines', 'sarreguemines', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Sarreguemines"}'::jsonb),
  ('57', 'Sarreguemines-Campagne', 'sarreguemines campagne', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Sarreguemines-Campagne"}'::jsonb),
  ('57', 'Stiring-Wendel', 'stiring wendel', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Stiring-Wendel"}'::jsonb),
  ('57', 'Vic-sur-Seille', 'vic sur seille', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Vic-sur-Seille"}'::jsonb),
  ('57', 'Volmunster', 'volmunster', 'B1', '{"department_code":"57","resolved_zone":"B1","canton_name":"Volmunster"}'::jsonb),
  ('57', 'Bitche', 'bitche', 'C1', '{"department_code":"57","resolved_zone":"C1","canton_name":"Bitche"}'::jsonb),
  ('57', 'Lorquin', 'lorquin', 'C1', '{"department_code":"57","resolved_zone":"C1","canton_name":"Lorquin"}'::jsonb),
  ('57', 'Phalsbourg', 'phalsbourg', 'C1', '{"department_code":"57","resolved_zone":"C1","canton_name":"Phalsbourg"}'::jsonb),
  ('57', 'Sarrebourg', 'sarrebourg', 'C1', '{"department_code":"57","resolved_zone":"C1","canton_name":"Sarrebourg"}'::jsonb),
  ('57', 'Tous les autres cantons', 'tous les autres cantons', 'A1', '{"department_code":"57","resolved_zone":"A1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('59', 'Avesnes-sur-Helpe (tous cantons)', 'avesnes sur helpe (tous cantons)', 'C1', '{"department_code":"59","resolved_zone":"C1","canton_name":"Avesnes-sur-Helpe (tous cantons)"}'::jsonb),
  ('59', 'Hautmont', 'hautmont', 'C1', '{"department_code":"59","resolved_zone":"C1","canton_name":"Hautmont"}'::jsonb),
  ('59', 'Maubeuge (tous cantons)', 'maubeuge (tous cantons)', 'C1', '{"department_code":"59","resolved_zone":"C1","canton_name":"Maubeuge (tous cantons)"}'::jsonb),
  ('59', 'Trélon', 'trelon', 'C1', '{"department_code":"59","resolved_zone":"C1","canton_name":"Trélon"}'::jsonb),
  ('59', 'Solre-le-Château', 'solre le chateau', 'C1', '{"department_code":"59","resolved_zone":"C1","canton_name":"Solre-le-Château"}'::jsonb),
  ('59', 'Tous les autres cantons', 'tous les autres cantons', 'A1', '{"department_code":"59","resolved_zone":"A1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('66', 'Mont-Louis', 'mont louis', 'C2', '{"department_code":"66","resolved_zone":"C2","canton_name":"Mont-Louis"}'::jsonb),
  ('66', 'Olette', 'olette', 'C2', '{"department_code":"66","resolved_zone":"C2","canton_name":"Olette"}'::jsonb),
  ('66', 'Saillegouse', 'saillegouse', 'C2', '{"department_code":"66","resolved_zone":"C2","canton_name":"Saillegouse"}'::jsonb),
  ('66', 'Tous les autres cantons', 'tous les autres cantons', 'D', '{"department_code":"66","resolved_zone":"D","canton_name":"Tous les autres cantons"}'::jsonb),
  ('67', 'Drulingen', 'drulingen', 'B1', '{"department_code":"67","resolved_zone":"B1","canton_name":"Drulingen"}'::jsonb),
  ('67', 'Sarre-Union', 'sarre union', 'B1', '{"department_code":"67","resolved_zone":"B1","canton_name":"Sarre-Union"}'::jsonb),
  ('67', 'Tous les autres cantons', 'tous les autres cantons', 'A1', '{"department_code":"67","resolved_zone":"A1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('70', 'Champagney', 'champagney', 'C1', '{"department_code":"70","resolved_zone":"C1","canton_name":"Champagney"}'::jsonb),
  ('70', 'Faucogney-et-la-Mer', 'faucogney et la mer', 'C1', '{"department_code":"70","resolved_zone":"C1","canton_name":"Faucogney-et-la-Mer"}'::jsonb),
  ('70', 'Héricourt', 'hericourt', 'C1', '{"department_code":"70","resolved_zone":"C1","canton_name":"Héricourt"}'::jsonb),
  ('70', 'Lure (tous cantons)', 'lure (tous cantons)', 'C1', '{"department_code":"70","resolved_zone":"C1","canton_name":"Lure (tous cantons)"}'::jsonb),
  ('70', 'Mélisey', 'melisey', 'C1', '{"department_code":"70","resolved_zone":"C1","canton_name":"Mélisey"}'::jsonb),
  ('70', 'Villersexel', 'villersexel', 'C1', '{"department_code":"70","resolved_zone":"C1","canton_name":"Villersexel"}'::jsonb),
  ('70', 'Tous les autres cantons', 'tous les autres cantons', 'B1', '{"department_code":"70","resolved_zone":"B1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('71', 'Beaurepaire-en-Bresse', 'beaurepaire en bresse', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Beaurepaire-en-Bresse"}'::jsonb),
  ('71', 'Cuisery', 'cuisery', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Cuisery"}'::jsonb),
  ('71', 'Cuiseaux', 'cuiseaux', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Cuiseaux"}'::jsonb),
  ('71', 'Louhans', 'louhans', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Louhans"}'::jsonb),
  ('71', 'Montpont-en-Bresse', 'montpont en bresse', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Montpont-en-Bresse"}'::jsonb),
  ('71', 'Montret', 'montret', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Montret"}'::jsonb),
  ('71', 'Pierre-de-Bresse', 'pierre de bresse', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Pierre-de-Bresse"}'::jsonb),
  ('71', 'Saint-Germain-du-Bois', 'saint germain du bois', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Saint-Germain-du-Bois"}'::jsonb),
  ('71', 'Tournus', 'tournus', 'B1', '{"department_code":"71","resolved_zone":"B1","canton_name":"Tournus"}'::jsonb),
  ('71', 'Tous les autres cantons', 'tous les autres cantons', 'A2', '{"department_code":"71","resolved_zone":"A2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('73', 'Aiguebelle', 'aiguebelle', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Aiguebelle"}'::jsonb),
  ('73', 'Aime', 'aime', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Aime"}'::jsonb),
  ('73', 'Albertville (tous cantons)', 'albertville (tous cantons)', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Albertville (tous cantons)"}'::jsonb),
  ('73', 'Beaufort', 'beaufort', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Beaufort"}'::jsonb),
  ('73', 'Bourg-Saint-Maurice', 'bourg saint maurice', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Bourg-Saint-Maurice"}'::jsonb),
  ('73', 'Bozel', 'bozel', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Bozel"}'::jsonb),
  ('73', 'Châtelard (le)', 'chatelard (le)', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Châtelard (le)"}'::jsonb),
  ('73', 'Chambre (la)', 'chambre (la)', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Chambre (la)"}'::jsonb),
  ('73', 'Chamoux-sur-Gelon', 'chamoux sur gelon', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Chamoux-sur-Gelon"}'::jsonb),
  ('73', 'Grésy-sur-Isère', 'gresy sur isere', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Grésy-sur-Isère"}'::jsonb),
  ('73', 'Lanslebourg-Mont-Cenis', 'lanslebourg mont cenis', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Lanslebourg-Mont-Cenis"}'::jsonb),
  ('73', 'Modane', 'modane', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Modane"}'::jsonb),
  ('73', 'Moûtiers', 'moutiers', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Moûtiers"}'::jsonb),
  ('73', 'Saint-Jean-de-Maurienne', 'saint jean de maurienne', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Saint-Jean-de-Maurienne"}'::jsonb),
  ('73', 'Saint-Michel-de-Maurienne', 'saint michel de maurienne', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Saint-Michel-de-Maurienne"}'::jsonb),
  ('73', 'Saint-Pierre-d''Albigny', 'saint pierre d albigny', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Saint-Pierre-d''Albigny"}'::jsonb),
  ('73', 'Rochette (la)', 'rochette (la)', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Rochette (la)"}'::jsonb),
  ('73', 'Ugine', 'ugine', 'E', '{"department_code":"73","resolved_zone":"E","canton_name":"Ugine"}'::jsonb),
  ('73', 'Tous les autres cantons', 'tous les autres cantons', 'C2', '{"department_code":"73","resolved_zone":"C2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('74', 'Alby-sur-Chéran', 'alby sur cheran', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Alby-sur-Chéran"}'::jsonb),
  ('74', 'Annemasse (tous cantons)', 'annemasse (tous cantons)', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Annemasse (tous cantons)"}'::jsonb),
  ('74', 'Boëge', 'boege', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Boëge"}'::jsonb),
  ('74', 'Cruseilles', 'cruseilles', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Cruseilles"}'::jsonb),
  ('74', 'Frangy', 'frangy', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Frangy"}'::jsonb),
  ('74', 'Douvaine', 'douvaine', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Douvaine"}'::jsonb),
  ('74', 'Reignier', 'reignier', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Reignier"}'::jsonb),
  ('74', 'Rumilly', 'rumilly', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Rumilly"}'::jsonb),
  ('74', 'Saint-Julien-en-Genevois', 'saint julien en genevois', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Saint-Julien-en-Genevois"}'::jsonb),
  ('74', 'Seyssel', 'seyssel', 'C2', '{"department_code":"74","resolved_zone":"C2","canton_name":"Seyssel"}'::jsonb),
  ('74', 'Tous les autres cantons', 'tous les autres cantons', 'E', '{"department_code":"74","resolved_zone":"E","canton_name":"Tous les autres cantons"}'::jsonb),
  ('81', 'Dourgne', 'dourgne', 'C2', '{"department_code":"81","resolved_zone":"C2","canton_name":"Dourgne"}'::jsonb),
  ('81', 'Labruguière', 'labruguiere', 'C2', '{"department_code":"81","resolved_zone":"C2","canton_name":"Labruguière"}'::jsonb),
  ('81', 'Mazamet (tous cantons)', 'mazamet (tous cantons)', 'C2', '{"department_code":"81","resolved_zone":"C2","canton_name":"Mazamet (tous cantons)"}'::jsonb),
  ('81', 'Saint-Amans-Soult', 'saint amans soult', 'C2', '{"department_code":"81","resolved_zone":"C2","canton_name":"Saint-Amans-Soult"}'::jsonb),
  ('81', 'Tous les autres cantons', 'tous les autres cantons', 'A2', '{"department_code":"81","resolved_zone":"A2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('83', 'Barjols', 'barjols', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Barjols"}'::jsonb),
  ('83', 'Besse-sur-Issole', 'besse sur issole', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Besse-sur-Issole"}'::jsonb),
  ('83', 'Brignoles', 'brignoles', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Brignoles"}'::jsonb),
  ('83', 'Cotignac', 'cotignac', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Cotignac"}'::jsonb),
  ('83', 'Fréjus', 'frejus', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Fréjus"}'::jsonb),
  ('83', 'Grimaud', 'grimaud', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Grimaud"}'::jsonb),
  ('83', 'Lorgues', 'lorgues', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Lorgues"}'::jsonb),
  ('83', 'Luc (le)', 'luc (le)', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Luc (le)"}'::jsonb),
  ('83', 'Muy (le)', 'muy (le)', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Muy (le)"}'::jsonb),
  ('83', 'Saint-Maximin-la-Sainte-Baume', 'saint maximin la sainte baume', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Saint-Maximin-la-Sainte-Baume"}'::jsonb),
  ('83', 'Saint-Raphaël', 'saint raphael', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Saint-Raphaël"}'::jsonb),
  ('83', 'Saint-Tropez', 'saint tropez', 'C2', '{"department_code":"83","resolved_zone":"C2","canton_name":"Saint-Tropez"}'::jsonb),
  ('83', 'Tous les autres cantons', 'tous les autres cantons', 'A2', '{"department_code":"83","resolved_zone":"A2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('84', 'Valréas', 'valreas', 'C2', '{"department_code":"84","resolved_zone":"C2","canton_name":"Valréas"}'::jsonb),
  ('84', 'Tous les autres cantons', 'tous les autres cantons', 'B2', '{"department_code":"84","resolved_zone":"B2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('88', 'Bulgnéville', 'bulgneville', 'A2', '{"department_code":"88","resolved_zone":"A2","canton_name":"Bulgnéville"}'::jsonb),
  ('88', 'Châtenois', 'chatenois', 'A2', '{"department_code":"88","resolved_zone":"A2","canton_name":"Châtenois"}'::jsonb),
  ('88', 'Coussey', 'coussey', 'A2', '{"department_code":"88","resolved_zone":"A2","canton_name":"Coussey"}'::jsonb),
  ('88', 'Lamarche', 'lamarche', 'A2', '{"department_code":"88","resolved_zone":"A2","canton_name":"Lamarche"}'::jsonb),
  ('88', 'Mirecourt', 'mirecourt', 'A2', '{"department_code":"88","resolved_zone":"A2","canton_name":"Mirecourt"}'::jsonb),
  ('88', 'Neufchâteau', 'neufchateau', 'A2', '{"department_code":"88","resolved_zone":"A2","canton_name":"Neufchâteau"}'::jsonb),
  ('88', 'Vittel', 'vittel', 'A2', '{"department_code":"88","resolved_zone":"A2","canton_name":"Vittel"}'::jsonb),
  ('88', 'Bains-les-Bains', 'bains les bains', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Bains-les-Bains"}'::jsonb),
  ('88', 'Bruyères', 'bruyeres', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Bruyères"}'::jsonb),
  ('88', 'Charmes', 'charmes', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Charmes"}'::jsonb),
  ('88', 'Châtel-sur-Moselle', 'chatel sur moselle', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Châtel-sur-Moselle"}'::jsonb),
  ('88', 'Darney', 'darney', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Darney"}'::jsonb),
  ('88', 'Dompaire', 'dompaire', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Dompaire"}'::jsonb),
  ('88', 'Épinal (tous cantons)', 'epinal (tous cantons)', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Épinal (tous cantons)"}'::jsonb),
  ('88', 'Monthureux-sur-Saône', 'monthureux sur saone', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Monthureux-sur-Saône"}'::jsonb),
  ('88', 'Plombières-les-Bains', 'plombieres les bains', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Plombières-les-Bains"}'::jsonb),
  ('88', 'Rambervillers', 'rambervillers', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Rambervillers"}'::jsonb),
  ('88', 'Remiremont', 'remiremont', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Remiremont"}'::jsonb),
  ('88', 'Xertigny', 'xertigny', 'B1', '{"department_code":"88","resolved_zone":"B1","canton_name":"Xertigny"}'::jsonb),
  ('88', 'Tous les autres cantons', 'tous les autres cantons', 'C2', '{"department_code":"88","resolved_zone":"C2","canton_name":"Tous les autres cantons"}'::jsonb)
ON CONFLICT (department_code, canton_name_normalized) DO UPDATE
SET canton_name = EXCLUDED.canton_name,
    resolved_zone = EXCLUDED.resolved_zone,
    source_payload = EXCLUDED.source_payload,
    updated_at = now();
