-- Climate seed data for Supabase
INSERT INTO public.mdall_climate_wind_canton_overrides (department_code, canton_name, canton_name_normalized, resolved_zone, source_payload)
VALUES
  ('01', 'Bâgé-le-Châtel', 'bage le chatel', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Bâgé-le-Châtel"}'::jsonb),
  ('01', 'Chalamont', 'chalamont', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Chalamont"}'::jsonb),
  ('01', 'Châtillon-sur-Chalaronne', 'chatillon sur chalaronne', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Châtillon-sur-Chalaronne"}'::jsonb),
  ('01', 'Coligny', 'coligny', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Coligny"}'::jsonb),
  ('01', 'Meximieux', 'meximieux', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Meximieux"}'::jsonb),
  ('01', 'Miribel', 'miribel', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Miribel"}'::jsonb),
  ('01', 'Montluel', 'montluel', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Montluel"}'::jsonb),
  ('01', 'Montrevel-en-Bresse', 'montrevel en bresse', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Montrevel-en-Bresse"}'::jsonb),
  ('01', 'Pont-de-Vaux', 'pont de vaux', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Pont-de-Vaux"}'::jsonb),
  ('01', 'Pont-de-Veyle', 'pont de veyle', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Pont-de-Veyle"}'::jsonb),
  ('01', 'Reyrieux', 'reyrieux', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Reyrieux"}'::jsonb),
  ('01', 'Saint-Triviers-de-Courtes', 'saint triviers de courtes', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Saint-Triviers-de-Courtes"}'::jsonb),
  ('01', 'Saint-Triviers-sur-Moignans', 'saint triviers sur moignans', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Saint-Triviers-sur-Moignans"}'::jsonb),
  ('01', 'Thoissey', 'thoissey', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Thoissey"}'::jsonb),
  ('01', 'Trévoux', 'trevoux', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Trévoux"}'::jsonb),
  ('01', 'Villars-les-Dombes', 'villars les dombes', '2', '{"department_code":"01","resolved_zone":"2","canton_name":"Villars-les-Dombes"}'::jsonb),
  ('01', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"01","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('04', 'Annot', 'annot', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Annot"}'::jsonb),
  ('04', 'Barcelonnette', 'barcelonnette', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Barcelonnette"}'::jsonb),
  ('04', 'Colmars', 'colmars', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Colmars"}'::jsonb),
  ('04', 'Entrevaux', 'entrevaux', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Entrevaux"}'::jsonb),
  ('04', 'Javie (la)', 'javie (la)', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Javie (la)"}'::jsonb),
  ('04', 'Lauzet-Ubaye (le)', 'lauzet ubaye (le)', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Lauzet-Ubaye (le)"}'::jsonb),
  ('04', 'Saint-André-les-Alpes', 'saint andre les alpes', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Saint-André-les-Alpes"}'::jsonb),
  ('04', 'Seyne', 'seyne', '1', '{"department_code":"04","resolved_zone":"1","canton_name":"Seyne"}'::jsonb),
  ('04', 'Tous les autres cantons', 'tous les autres cantons', '2', '{"department_code":"04","resolved_zone":"2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('05', 'Aspres-sur-Buëch', 'aspres sur buech', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Aspres-sur-Buëch"}'::jsonb),
  ('05', 'Barcillonnette', 'barcillonnette', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Barcillonnette"}'::jsonb),
  ('05', 'Laragne-Montéglin', 'laragne monteglin', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Laragne-Montéglin"}'::jsonb),
  ('05', 'Orpierre', 'orpierre', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Orpierre"}'::jsonb),
  ('05', 'Ribiers', 'ribiers', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Ribiers"}'::jsonb),
  ('05', 'Rosans', 'rosans', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Rosans"}'::jsonb),
  ('05', 'Serres', 'serres', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Serres"}'::jsonb),
  ('05', 'Tallard', 'tallard', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Tallard"}'::jsonb),
  ('05', 'Veynes', 'veynes', '2', '{"department_code":"05","resolved_zone":"2","canton_name":"Veynes"}'::jsonb),
  ('05', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"05","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('06', 'Guillaumes', 'guillaumes', '1', '{"department_code":"06","resolved_zone":"1","canton_name":"Guillaumes"}'::jsonb),
  ('06', 'Puget-Théniers', 'puget theniers', '1', '{"department_code":"06","resolved_zone":"1","canton_name":"Puget-Théniers"}'::jsonb),
  ('06', 'Saint-Étienne-de-Tinée', 'saint etienne de tinee', '1', '{"department_code":"06","resolved_zone":"1","canton_name":"Saint-Étienne-de-Tinée"}'::jsonb),
  ('06', 'Saint-Martin-Vésubie', 'saint martin vesubie', '1', '{"department_code":"06","resolved_zone":"1","canton_name":"Saint-Martin-Vésubie"}'::jsonb),
  ('06', 'Saint-Sauveur-sur-Tinée', 'saint sauveur sur tinee', '1', '{"department_code":"06","resolved_zone":"1","canton_name":"Saint-Sauveur-sur-Tinée"}'::jsonb),
  ('06', 'Villars-sur-Var', 'villars sur var', '1', '{"department_code":"06","resolved_zone":"1","canton_name":"Villars-sur-Var"}'::jsonb),
  ('06', 'Tous les autres cantons', 'tous les autres cantons', '2', '{"department_code":"06","resolved_zone":"2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('11', 'Alaigne', 'alaigne', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Alaigne"}'::jsonb),
  ('11', 'Alzonne', 'alzonne', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Alzonne"}'::jsonb),
  ('11', 'Belpech', 'belpech', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Belpech"}'::jsonb),
  ('11', 'Carcassonne (tous cantons)', 'carcassonne (tous cantons)', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Carcassonne (tous cantons)"}'::jsonb),
  ('11', 'Castelnaudary (tous cantons)', 'castelnaudary (tous cantons)', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Castelnaudary (tous cantons)"}'::jsonb),
  ('11', 'Chalabre', 'chalabre', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Chalabre"}'::jsonb),
  ('11', 'Conques-sur-Orbiel', 'conques sur orbiel', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Conques-sur-Orbiel"}'::jsonb),
  ('11', 'Fanjeaux', 'fanjeaux', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Fanjeaux"}'::jsonb),
  ('11', 'Limoux', 'limoux', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Limoux"}'::jsonb),
  ('11', 'Mas-Cabardès', 'mas cabardes', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Mas-Cabardès"}'::jsonb),
  ('11', 'Montréal', 'montreal', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Montréal"}'::jsonb),
  ('11', 'Saissac', 'saissac', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Saissac"}'::jsonb),
  ('11', 'Salles-sur-l''Hers', 'salles sur l hers', '2', '{"department_code":"11","resolved_zone":"2","canton_name":"Salles-sur-l''Hers"}'::jsonb),
  ('11', 'Tous les autres cantons', 'tous les autres cantons', '3', '{"department_code":"11","resolved_zone":"3","canton_name":"Tous les autres cantons"}'::jsonb),
  ('15', 'Allanche', 'allanche', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Allanche"}'::jsonb),
  ('15', 'Chaudes-Aigues', 'chaudes aigues', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Chaudes-Aigues"}'::jsonb),
  ('15', 'Condat', 'condat', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Condat"}'::jsonb),
  ('15', 'Massiac', 'massiac', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Massiac"}'::jsonb),
  ('15', 'Murat', 'murat', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Murat"}'::jsonb),
  ('15', 'Pierrefort', 'pierrefort', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Pierrefort"}'::jsonb),
  ('15', 'Ruynes-en-Margeride', 'ruynes en margeride', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Ruynes-en-Margeride"}'::jsonb),
  ('15', 'Saint-Flour (tous cantons)', 'saint flour (tous cantons)', '2', '{"department_code":"15","resolved_zone":"2","canton_name":"Saint-Flour (tous cantons)"}'::jsonb),
  ('15', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"15","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('17', 'Montendre', 'montendre', '1', '{"department_code":"17","resolved_zone":"1","canton_name":"Montendre"}'::jsonb),
  ('17', 'Montguyon', 'montguyon', '1', '{"department_code":"17","resolved_zone":"1","canton_name":"Montguyon"}'::jsonb),
  ('17', 'Montlieu-la-Garde', 'montlieu la garde', '1', '{"department_code":"17","resolved_zone":"1","canton_name":"Montlieu-la-Garde"}'::jsonb),
  ('17', 'Archiac', 'archiac', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Archiac"}'::jsonb),
  ('17', 'Aulnay', 'aulnay', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Aulnay"}'::jsonb),
  ('17', 'Burie', 'burie', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Burie"}'::jsonb),
  ('17', 'Cozes', 'cozes', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Cozes"}'::jsonb),
  ('17', 'Gémozac', 'gemozac', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Gémozac"}'::jsonb),
  ('17', 'Jonzac', 'jonzac', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Jonzac"}'::jsonb),
  ('17', 'Loulay', 'loulay', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Loulay"}'::jsonb),
  ('17', 'Matha', 'matha', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Matha"}'::jsonb),
  ('17', 'Mirambeau', 'mirambeau', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Mirambeau"}'::jsonb),
  ('17', 'Pons', 'pons', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Pons"}'::jsonb),
  ('17', 'Saintes (tous cantons)', 'saintes (tous cantons)', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Saintes (tous cantons)"}'::jsonb),
  ('17', 'Saint-Genis-de-Saintonge', 'saint genis de saintonge', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Saint-Genis-de-Saintonge"}'::jsonb),
  ('17', 'Saint-Hilaire-de-Villefranche', 'saint hilaire de villefranche', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Saint-Hilaire-de-Villefranche"}'::jsonb),
  ('17', 'Saint-Jean-d''Angély', 'saint jean d angely', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Saint-Jean-d''Angély"}'::jsonb),
  ('17', 'Saint-Porchaire', 'saint porchaire', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Saint-Porchaire"}'::jsonb),
  ('17', 'Saint-Savinien', 'saint savinien', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Saint-Savinien"}'::jsonb),
  ('17', 'Saujon', 'saujon', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Saujon"}'::jsonb),
  ('17', 'Tonnay-Boutonne', 'tonnay boutonne', '2', '{"department_code":"17","resolved_zone":"2","canton_name":"Tonnay-Boutonne"}'::jsonb),
  ('17', 'Tous les autres cantons', 'tous les autres cantons', '3', '{"department_code":"17","resolved_zone":"3","canton_name":"Tous les autres cantons"}'::jsonb),
  ('2A', 'Bonifacio', 'bonifacio', '4', '{"department_code":"2A","resolved_zone":"4","canton_name":"Bonifacio"}'::jsonb),
  ('2A', 'Figari', 'figari', '4', '{"department_code":"2A","resolved_zone":"4","canton_name":"Figari"}'::jsonb),
  ('2A', 'Levie', 'levie', '4', '{"department_code":"2A","resolved_zone":"4","canton_name":"Levie"}'::jsonb),
  ('2A', 'Porto-Vecchio', 'porto vecchio', '4', '{"department_code":"2A","resolved_zone":"4","canton_name":"Porto-Vecchio"}'::jsonb),
  ('2A', 'Serra-di-Scopamène', 'serra di scopamene', '4', '{"department_code":"2A","resolved_zone":"4","canton_name":"Serra-di-Scopamène"}'::jsonb),
  ('2A', 'Tous les autres cantons', 'tous les autres cantons', '3', '{"department_code":"2A","resolved_zone":"3","canton_name":"Tous les autres cantons"}'::jsonb),
  ('2B', 'Belgodère', 'belgodere', '3', '{"department_code":"2B","resolved_zone":"3","canton_name":"Belgodère"}'::jsonb),
  ('2B', 'Calenzana', 'calenzana', '3', '{"department_code":"2B","resolved_zone":"3","canton_name":"Calenzana"}'::jsonb),
  ('2B', 'Calvi', 'calvi', '3', '{"department_code":"2B","resolved_zone":"3","canton_name":"Calvi"}'::jsonb),
  ('2B', 'Île-Rousse (l'')', 'ile rousse (l )', '3', '{"department_code":"2B","resolved_zone":"3","canton_name":"Île-Rousse (l'')"}'::jsonb),
  ('2B', 'Tous les autres cantons', 'tous les autres cantons', '4', '{"department_code":"2B","resolved_zone":"4","canton_name":"Tous les autres cantons"}'::jsonb),
  ('21', 'Auxonne', 'auxonne', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Auxonne"}'::jsonb),
  ('21', 'Chenôve', 'chenove', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Chenôve"}'::jsonb),
  ('21', 'Dijon (tous cantons)', 'dijon (tous cantons)', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Dijon (tous cantons)"}'::jsonb),
  ('21', 'Fontaine-Française', 'fontaine francaise', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Fontaine-Française"}'::jsonb),
  ('21', 'Fontaine-les-Dijon', 'fontaine les dijon', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Fontaine-les-Dijon"}'::jsonb),
  ('21', 'Genlis', 'genlis', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Genlis"}'::jsonb),
  ('21', 'Grancey-le-Château-Neuvelle', 'grancey le chateau neuvelle', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Grancey-le-Château-Neuvelle"}'::jsonb),
  ('21', 'Is-sur-Tille', 'is sur tille', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Is-sur-Tille"}'::jsonb),
  ('21', 'Mirebeau-sur-Bèze', 'mirebeau sur beze', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Mirebeau-sur-Bèze"}'::jsonb),
  ('21', 'Pontailler-sur-Saône', 'pontailler sur saone', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Pontailler-sur-Saône"}'::jsonb),
  ('21', 'Saint-Jean-de-Losne', 'saint jean de losne', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Saint-Jean-de-Losne"}'::jsonb),
  ('21', 'Saint-Seine-l''Abbaye', 'saint seine l abbaye', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Saint-Seine-l''Abbaye"}'::jsonb),
  ('21', 'Selongey', 'selongey', '1', '{"department_code":"21","resolved_zone":"1","canton_name":"Selongey"}'::jsonb),
  ('21', 'Tous les autres cantons', 'tous les autres cantons', '2', '{"department_code":"21","resolved_zone":"2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('25', 'Audincourt', 'audincourt', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Audincourt"}'::jsonb),
  ('25', 'Clerval', 'clerval', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Clerval"}'::jsonb),
  ('25', 'Etupes', 'etupes', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Etupes"}'::jsonb),
  ('25', 'Hérimoncourt', 'herimoncourt', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Hérimoncourt"}'::jsonb),
  ('25', 'Isle-sur-le-Doubs (l'')', 'isle sur le doubs (l )', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Isle-sur-le-Doubs (l'')"}'::jsonb),
  ('25', 'Maîche', 'maiche', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Maîche"}'::jsonb),
  ('25', 'Montbéliard (tous cantons)', 'montbeliard (tous cantons)', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Montbéliard (tous cantons)"}'::jsonb),
  ('25', 'Pont-de-Roide', 'pont de roide', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Pont-de-Roide"}'::jsonb),
  ('25', 'Saint-Hippolyte', 'saint hippolyte', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Saint-Hippolyte"}'::jsonb),
  ('25', 'Sochaux', 'sochaux', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Sochaux"}'::jsonb),
  ('25', 'Valentigney', 'valentigney', '2', '{"department_code":"25","resolved_zone":"2","canton_name":"Valentigney"}'::jsonb),
  ('25', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"25","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('30', 'Aigues-Mortes', 'aigues mortes', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Aigues-Mortes"}'::jsonb),
  ('30', 'Aimargues', 'aimargues', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Aimargues"}'::jsonb),
  ('30', 'Aramon', 'aramon', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Aramon"}'::jsonb),
  ('30', 'Beaucaire', 'beaucaire', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Beaucaire"}'::jsonb),
  ('30', 'Bouillargues', 'bouillargues', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Bouillargues"}'::jsonb),
  ('30', 'Saint-Gilles', 'saint gilles', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Saint-Gilles"}'::jsonb),
  ('30', 'Marguerittes', 'marguerittes', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Marguerittes"}'::jsonb),
  ('30', 'Nîmes (tous cantons)', 'nimes (tous cantons)', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Nîmes (tous cantons)"}'::jsonb),
  ('30', 'Quissac', 'quissac', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Quissac"}'::jsonb),
  ('30', 'Saint-Mamert-du-Gard', 'saint mamert du gard', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Saint-Mamert-du-Gard"}'::jsonb),
  ('30', 'Sommières', 'sommieres', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Sommières"}'::jsonb),
  ('30', 'Vauvert', 'vauvert', '3', '{"department_code":"30","resolved_zone":"3","canton_name":"Vauvert"}'::jsonb),
  ('30', 'Tous les autres cantons', 'tous les autres cantons', '2', '{"department_code":"30","resolved_zone":"2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('31', 'Auterive', 'auterive', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Auterive"}'::jsonb),
  ('31', 'Caraman', 'caraman', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Caraman"}'::jsonb),
  ('31', 'Cintegabelle', 'cintegabelle', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Cintegabelle"}'::jsonb),
  ('31', 'Lanta', 'lanta', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Lanta"}'::jsonb),
  ('31', 'Montgiscard', 'montgiscard', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Montgiscard"}'::jsonb),
  ('31', 'Nailloux', 'nailloux', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Nailloux"}'::jsonb),
  ('31', 'Revel', 'revel', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Revel"}'::jsonb),
  ('31', 'Villefranche-de-Lauragais', 'villefranche de lauragais', '2', '{"department_code":"31","resolved_zone":"2","canton_name":"Villefranche-de-Lauragais"}'::jsonb),
  ('31', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"31","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('33', 'Castelnau-de-Médoc', 'castelnau de medoc', '2', '{"department_code":"33","resolved_zone":"2","canton_name":"Castelnau-de-Médoc"}'::jsonb),
  ('33', 'Lesparre-Médoc', 'lesparre medoc', '2', '{"department_code":"33","resolved_zone":"2","canton_name":"Lesparre-Médoc"}'::jsonb),
  ('33', 'Pauillac', 'pauillac', '2', '{"department_code":"33","resolved_zone":"2","canton_name":"Pauillac"}'::jsonb),
  ('33', 'Saint-Laurent-Médoc', 'saint laurent medoc', '2', '{"department_code":"33","resolved_zone":"2","canton_name":"Saint-Laurent-Médoc"}'::jsonb),
  ('33', 'Saint-Vivien-de-Médoc', 'saint vivien de medoc', '2', '{"department_code":"33","resolved_zone":"2","canton_name":"Saint-Vivien-de-Médoc"}'::jsonb),
  ('33', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"33","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('38', 'Beaurepaire', 'beaurepaire', '2', '{"department_code":"38","resolved_zone":"2","canton_name":"Beaurepaire"}'::jsonb),
  ('38', 'Heyrieux', 'heyrieux', '2', '{"department_code":"38","resolved_zone":"2","canton_name":"Heyrieux"}'::jsonb),
  ('38', 'Saint-Jean-de-Bournay', 'saint jean de bournay', '2', '{"department_code":"38","resolved_zone":"2","canton_name":"Saint-Jean-de-Bournay"}'::jsonb),
  ('38', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"38","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('40', 'Amou', 'amou', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Amou"}'::jsonb),
  ('40', 'Castets', 'castets', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Castets"}'::jsonb),
  ('40', 'Dax (tous cantons)', 'dax (tous cantons)', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Dax (tous cantons)"}'::jsonb),
  ('40', 'Montfort-en-Chalosse', 'montfort en chalosse', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Montfort-en-Chalosse"}'::jsonb),
  ('40', 'Mugron', 'mugron', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Mugron"}'::jsonb),
  ('40', 'Peyrehorade', 'peyrehorade', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Peyrehorade"}'::jsonb),
  ('40', 'Pouillon', 'pouillon', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Pouillon"}'::jsonb),
  ('40', 'Saint-Martin-de-Seignanx', 'saint martin de seignanx', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Saint-Martin-de-Seignanx"}'::jsonb),
  ('40', 'Saint-Vincent-de-Tyrosse', 'saint vincent de tyrosse', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Saint-Vincent-de-Tyrosse"}'::jsonb),
  ('40', 'Soustons', 'soustons', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Soustons"}'::jsonb),
  ('40', 'Tartas (tous cantons)', 'tartas (tous cantons)', '2', '{"department_code":"40","resolved_zone":"2","canton_name":"Tartas (tous cantons)"}'::jsonb),
  ('40', 'Tous les autres cantons', 'tous les autres cantons', '1', '{"department_code":"40","resolved_zone":"1","canton_name":"Tous les autres cantons"}'::jsonb),
  ('44', 'Ancenis', 'ancenis', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Ancenis"}'::jsonb),
  ('44', 'Blain', 'blain', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Blain"}'::jsonb),
  ('44', 'Châteaubriant', 'chateaubriant', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Châteaubriant"}'::jsonb),
  ('44', 'Derval', 'derval', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Derval"}'::jsonb),
  ('44', 'Guémené-Penfao', 'guemene penfao', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Guémené-Penfao"}'::jsonb),
  ('44', 'Ligné', 'ligne', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Ligné"}'::jsonb),
  ('44', 'Moisdon-la-Rivière', 'moisdon la riviere', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Moisdon-la-Rivière"}'::jsonb),
  ('44', 'Nort-sur-Erdre', 'nort sur erdre', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Nort-sur-Erdre"}'::jsonb),
  ('44', 'Nozay', 'nozay', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Nozay"}'::jsonb),
  ('44', 'Riaillé', 'riaille', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Riaillé"}'::jsonb),
  ('44', 'Rougé', 'rouge', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Rougé"}'::jsonb),
  ('44', 'Saint-Julien-de-Vouvantes', 'saint julien de vouvantes', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Saint-Julien-de-Vouvantes"}'::jsonb),
  ('44', 'Saint-Marc-la-Jaille', 'saint marc la jaille', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Saint-Marc-la-Jaille"}'::jsonb),
  ('44', 'Saint-Nicolas-de-Redon', 'saint nicolas de redon', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Saint-Nicolas-de-Redon"}'::jsonb),
  ('44', 'Varades', 'varades', '2', '{"department_code":"44","resolved_zone":"2","canton_name":"Varades"}'::jsonb),
  ('44', 'Tous les autres cantons', 'tous les autres cantons', '3', '{"department_code":"44","resolved_zone":"3","canton_name":"Tous les autres cantons"}'::jsonb),
  ('59', 'Arleux', 'arleux', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Arleux"}'::jsonb),
  ('59', 'Anzin', 'anzin', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Anzin"}'::jsonb),
  ('59', 'Avesnes-sur-Helpe (tous cantons)', 'avesnes sur helpe (tous cantons)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Avesnes-sur-Helpe (tous cantons)"}'::jsonb),
  ('59', 'Bavay', 'bavay', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Bavay"}'::jsonb),
  ('59', 'Berlaimont', 'berlaimont', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Berlaimont"}'::jsonb),
  ('59', 'Bouchain', 'bouchain', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Bouchain"}'::jsonb),
  ('59', 'Cambrai (tous cantons)', 'cambrai (tous cantons)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Cambrai (tous cantons)"}'::jsonb),
  ('59', 'Carnières', 'carnieres', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Carnières"}'::jsonb),
  ('59', 'Cateau-Cambrésis (le)', 'cateau cambresis (le)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Cateau-Cambrésis (le)"}'::jsonb),
  ('59', 'Clary', 'clary', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Clary"}'::jsonb),
  ('59', 'Condé-sur-l''Escaut', 'conde sur l escaut', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Condé-sur-l''Escaut"}'::jsonb),
  ('59', 'Denain', 'denain', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Denain"}'::jsonb),
  ('59', 'Douai (tous cantons)', 'douai (tous cantons)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Douai (tous cantons)"}'::jsonb),
  ('59', 'Hautmont', 'hautmont', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Hautmont"}'::jsonb),
  ('59', 'Landrecies', 'landrecies', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Landrecies"}'::jsonb),
  ('59', 'Marchiennes', 'marchiennes', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Marchiennes"}'::jsonb),
  ('59', 'Marcoing', 'marcoing', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Marcoing"}'::jsonb),
  ('59', 'Maubeuge (tous cantons)', 'maubeuge (tous cantons)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Maubeuge (tous cantons)"}'::jsonb),
  ('59', 'Solre-le-Château', 'solre le chateau', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Solre-le-Château"}'::jsonb),
  ('59', 'Orchies', 'orchies', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Orchies"}'::jsonb),
  ('59', 'Quesnoy (le) (tous cantons)', 'quesnoy (le) (tous cantons)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Quesnoy (le) (tous cantons)"}'::jsonb),
  ('59', 'Saint-Amand-les-Eaux (tous cantons)', 'saint amand les eaux (tous cantons)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Saint-Amand-les-Eaux (tous cantons)"}'::jsonb),
  ('59', 'Solesmes', 'solesmes', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Solesmes"}'::jsonb),
  ('59', 'Trélon', 'trelon', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Trélon"}'::jsonb),
  ('59', 'Valenciennes (tous cantons)', 'valenciennes (tous cantons)', '2', '{"department_code":"59","resolved_zone":"2","canton_name":"Valenciennes (tous cantons)"}'::jsonb),
  ('59', 'Tous les autres cantons', 'tous les autres cantons', '3', '{"department_code":"59","resolved_zone":"3","canton_name":"Tous les autres cantons"}'::jsonb),
  ('62', 'Bapaume', 'bapaume', '2', '{"department_code":"62","resolved_zone":"2","canton_name":"Bapaume"}'::jsonb),
  ('62', 'Bertincourt', 'bertincourt', '2', '{"department_code":"62","resolved_zone":"2","canton_name":"Bertincourt"}'::jsonb),
  ('62', 'Croisilles', 'croisilles', '2', '{"department_code":"62","resolved_zone":"2","canton_name":"Croisilles"}'::jsonb),
  ('62', 'Marquion', 'marquion', '2', '{"department_code":"62","resolved_zone":"2","canton_name":"Marquion"}'::jsonb),
  ('62', 'Vitry-en-Artois', 'vitry en artois', '2', '{"department_code":"62","resolved_zone":"2","canton_name":"Vitry-en-Artois"}'::jsonb),
  ('62', 'Tous les autres cantons', 'tous les autres cantons', '3', '{"department_code":"62","resolved_zone":"3","canton_name":"Tous les autres cantons"}'::jsonb),
  ('70', 'Autrey-lès-Gray', 'autrey les gray', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Autrey-lès-Gray"}'::jsonb),
  ('70', 'Champlitte', 'champlitte', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Champlitte"}'::jsonb),
  ('70', 'Dampierre-sur-Salon', 'dampierre sur salon', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Dampierre-sur-Salon"}'::jsonb),
  ('70', 'Fresne-Saint-Mamès', 'fresne saint mames', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Fresne-Saint-Mamès"}'::jsonb),
  ('70', 'Gray', 'gray', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Gray"}'::jsonb),
  ('70', 'Gy', 'gy', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Gy"}'::jsonb),
  ('70', 'Marnay', 'marnay', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Marnay"}'::jsonb),
  ('70', 'Montbozon', 'montbozon', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Montbozon"}'::jsonb),
  ('70', 'Pesmes', 'pesmes', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Pesmes"}'::jsonb),
  ('70', 'Rioz', 'rioz', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Rioz"}'::jsonb),
  ('70', 'Scey-sur-Saône-et-Saint-Albin', 'scey sur saone et saint albin', '1', '{"department_code":"70","resolved_zone":"1","canton_name":"Scey-sur-Saône-et-Saint-Albin"}'::jsonb),
  ('70', 'Tous les autres cantons', 'tous les autres cantons', '2', '{"department_code":"70","resolved_zone":"2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('76', 'Bacqueville-en-Caux', 'bacqueville en caux', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Bacqueville-en-Caux"}'::jsonb),
  ('76', 'Blangy-sur-Bresle', 'blangy sur bresle', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Blangy-sur-Bresle"}'::jsonb),
  ('76', 'Cany-Barville', 'cany barville', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Cany-Barville"}'::jsonb),
  ('76', 'Eu', 'eu', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Eu"}'::jsonb),
  ('76', 'Dieppe (tous cantons)', 'dieppe (tous cantons)', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Dieppe (tous cantons)"}'::jsonb),
  ('76', 'Envermeu', 'envermeu', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Envermeu"}'::jsonb),
  ('76', 'Fontaine-le-Dun', 'fontaine le dun', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Fontaine-le-Dun"}'::jsonb),
  ('76', 'Offranville', 'offranville', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Offranville"}'::jsonb),
  ('76', 'Saint-Valery-en-Caux', 'saint valery en caux', '3', '{"department_code":"76","resolved_zone":"3","canton_name":"Saint-Valery-en-Caux"}'::jsonb),
  ('76', 'Tous les autres cantons', 'tous les autres cantons', '2', '{"department_code":"76","resolved_zone":"2","canton_name":"Tous les autres cantons"}'::jsonb),
  ('80', 'Ailly-sur-Noye', 'ailly sur noye', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Ailly-sur-Noye"}'::jsonb),
  ('80', 'Albert', 'albert', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Albert"}'::jsonb),
  ('80', 'Bray-sur-Somme', 'bray sur somme', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Bray-sur-Somme"}'::jsonb),
  ('80', 'Chaulnes', 'chaulnes', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Chaulnes"}'::jsonb),
  ('80', 'Combles', 'combles', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Combles"}'::jsonb),
  ('80', 'Ham', 'ham', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Ham"}'::jsonb),
  ('80', 'Montdidier', 'montdidier', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Montdidier"}'::jsonb),
  ('80', 'Moreil', 'moreil', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Moreil"}'::jsonb),
  ('80', 'Nesle', 'nesle', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Nesle"}'::jsonb),
  ('80', 'Péronne', 'peronne', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Péronne"}'::jsonb),
  ('80', 'Roisel', 'roisel', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Roisel"}'::jsonb),
  ('80', 'Rosières-en-Santerre', 'rosieres en santerre', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Rosières-en-Santerre"}'::jsonb),
  ('80', 'Roye', 'roye', '2', '{"department_code":"80","resolved_zone":"2","canton_name":"Roye"}'::jsonb),
  ('80', 'Tous les autres cantons', 'tous les autres cantons', '3', '{"department_code":"80","resolved_zone":"3","canton_name":"Tous les autres cantons"}'::jsonb),
  ('81', 'Cadalen', 'cadalen', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Cadalen"}'::jsonb),
  ('81', 'Castelnau-de-Montmiral', 'castelnau de montmiral', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Castelnau-de-Montmiral"}'::jsonb),
  ('81', 'Cordes-sur-Ciel', 'cordes sur ciel', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Cordes-sur-Ciel"}'::jsonb),
  ('81', 'Gaillac', 'gaillac', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Gaillac"}'::jsonb),
  ('81', 'Graulhet', 'graulhet', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Graulhet"}'::jsonb),
  ('81', 'Lavaur', 'lavaur', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Lavaur"}'::jsonb),
  ('81', 'Lisle-sur-Tarn', 'lisle sur tarn', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Lisle-sur-Tarn"}'::jsonb),
  ('81', 'Rabastens', 'rabastens', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Rabastens"}'::jsonb),
  ('81', 'Saint-Paul-Cap-de-Joux', 'saint paul cap de joux', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Saint-Paul-Cap-de-Joux"}'::jsonb),
  ('81', 'Salvagnac', 'salvagnac', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Salvagnac"}'::jsonb),
  ('81', 'Vaour', 'vaour', '1', '{"department_code":"81","resolved_zone":"1","canton_name":"Vaour"}'::jsonb),
  ('81', 'Tous les autres cantons', 'tous les autres cantons', '2', '{"department_code":"81","resolved_zone":"2","canton_name":"Tous les autres cantons"}'::jsonb)
ON CONFLICT (department_code, canton_name_normalized) DO UPDATE
SET canton_name = EXCLUDED.canton_name,
    resolved_zone = EXCLUDED.resolved_zone,
    source_payload = EXCLUDED.source_payload,
    updated_at = now();
