create table if not exists public.analysis_runs (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references public.projects(id) on delete cascade,
    document_id uuid not null references public.documents(id) on delete cascade,
    status text not null default 'queued',
    trigger_source text not null default 'manual',
    extractor_version text,
    pipeline_version text,
    prompt_version text,
    llm_model text,
    started_at timestamptz,
    finished_at timestamptz,
    error_message text,
    raw_text text,
    normalized_text_json jsonb,
    llm_output_raw jsonb,
    structured_output_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
