alter table public.subjects
  add column if not exists situation_id uuid,
  add column if not exists milestone_id uuid,
  add column if not exists parent_subject_id uuid,
  add column if not exists duplicate_of_subject_id uuid,
  add column if not exists replaced_by_subject_id uuid,
  add column if not exists origin_subject_observation_id uuid,
  add column if not exists assignee_user_id uuid,
  add column if not exists subject_type text,
  add column if not exists current_title text,
  add column if not exists current_description text,
  add column if not exists priority text,
  add column if not exists status text,
  add column if not exists closure_reason text,
  add column if not exists normalized_title text,
  add column if not exists normalized_description text,
  add column if not exists dedup_key text,
  add column if not exists closed_at timestamptz;
