-- L'archive quitte la console : les trois tables s'en vont, et le casier se ferme.
--
-- POURQUOI ON RETIRE CE QU'ON VIENT D'ÉCRIRE
--
-- La console avait construit sa propre chaîne : déposer des `.msg`, en tirer
-- des messages et des pièces, les ranger dans trois tables à elle, et lire un
-- épisode de cet ensemble. C'était une **seconde application**, avec ses
-- écrans, son casier et sa mémoire — et l'application, elle, savait déjà tout
-- faire. Ce qui manquait n'était pas un atelier : c'était de pouvoir verser
-- deux cents mails d'un coup dans un projet (`docs/nourrir-mdall.md`, § 8
-- quinquies).
--
-- Le dépouillement rejoint donc Fichiers, et l'épisode rejoint les
-- Indicateurs. Ces trois tables n'ont plus personne pour les lire, et une table
-- que rien ne lit finit par contenir une vérité qu'on croit encore.
--
-- ON NE VÉRIFIE PAS QU'ELLES SONT VIDES, ET C'EST UNE DÉCISION PRISE
--
-- La note du § 8 quinquies prévoyait de le vérifier. Le propriétaire de la base
-- a levé la réserve : lui seul y a versé, quelques messages d'essai, sans
-- valeur. Un `drop` conditionnel aurait ici laissé la migration échouer sur des
-- lignes dont on sait déjà qu'on n'en veut pas, et une migration qui échoue à
-- moitié laisse un schéma qu'on ne sait plus décrire.
--
-- CE QUE CETTE MIGRATION N'EST PAS
--
-- Elle n'est pas additive, et c'est assumé : elle **retire**. La règle
-- additive protège une donnée dont quelqu'un dépend. Ici personne n'en dépend,
-- et la garder coûterait plus que de la perdre — un casier ouvert de plus à
-- surveiller, trois tables de plus à expliquer.
--
-- Elle n'est pas non plus **complète** : le casier de stockage ne se supprime
-- pas en SQL, et la section 2 dit pourquoi et ce qui reste à faire à la main.

-- 1. Le lien d'abord. Il pointe vers les deux autres : le supprimer en dernier
--    obligerait à une cascade, et une cascade emporte ce qu'on n'a pas nommé.
--
--    **Les politiques ne se suppriment pas à part** : elles appartiennent à
--    leur table et partent avec elle. La première écriture les nommait
--    au-dessus de chaque `drop table`, ce qui ne servait à rien — et devenait
--    un piège au deuxième passage : ce fichier a échoué plus bas, sur le
--    casier (section 2), donc il sera rejoué. Un `drop policy` sur une table
--    déjà partie n'est pas le cas que `if exists` protège.
drop table if exists public.pieces_des_messages;
drop table if exists public.messages_archives;
drop table if exists public.pieces_archivees;

-- 2. Le casier : on lui retire ses portes, et c'est tout ce qu'une migration
--    peut faire.
--
--    LA PREMIÈRE ÉCRITURE DE CETTE SECTION A ÉTÉ REFUSÉE AU DÉPLOIEMENT
--
--    Elle supprimait les objets, puis le casier :
--
--        delete from storage.objects where bucket_id = 'archives';
--        delete from storage.buckets where id = 'archives';
--
--    et la base a répondu :
--
--        ERROR: Direct deletion from storage tables is not allowed.
--        Use the Storage API instead. (SQLSTATE 42501)
--
--    C'est une garde de Supabase, et elle a raison : un objet supprimé par un
--    `delete` laisse ses octets dans le stockage de fond, qui ne connaît que
--    l'API. La ligne disparaîtrait, le fichier resterait — un casier vide en
--    apparence, plein en vérité. Pour de la correspondance, c'est exactement
--    le contraire de ce qu'on veut.
--
--    CE QUE FAIT CETTE MIGRATION, ET CE QU'ELLE LAISSE À FAIRE
--
--    Elle retire les deux politiques du casier `archives`. Sans elles, plus
--    aucun jeton n'ouvre ce casier : ni en lecture, ni en écriture. Il devient
--    inatteignable, et il le reste.
--
--    Elle **ne le supprime pas**, et ne prétend pas le faire. Vider le casier
--    puis l'effacer est un geste de l'API de stockage — dans Supabase Studio,
--    Storage → archives → tout sélectionner → supprimer, puis supprimer le
--    casier. Tant que ce geste n'est pas fait, les quelques messages d'essai
--    sont toujours là, hors d'atteinte mais présents (règle 5 : on le dit
--    plutôt que de laisser croire qu'ils sont partis).
drop policy if exists storage_archives_administrateur_select on storage.objects;
drop policy if exists storage_archives_administrateur_insert on storage.objects;

-- 3. `est_administrateur()` part aussi, et il a fallu le vérifier pour le dire.
--
--    Elle avait l'air d'un bien commun — « la porte de la console s'en sert ».
--    Non : la porte se lit en JavaScript par un `select` borné sur la table des
--    administrateurs (`la-porte-de-la-console-supabase.js`), et les quatre
--    politiques de l'archive étaient ses seuls appelants. Elle n'en a plus
--    aucun.
--
--    Une fonction `security definer` que rien n'appelle est le pire des deux
--    mondes : elle ne sert à personne, et elle contourne une politique de
--    lecture. Le jour où quelqu'un la retrouvera, il la croira éprouvée. Sa
--    définition est dans l'historique ; la table des administrateurs, elle,
--    reste intacte.
drop function if exists public.est_administrateur();
